#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace thi_de2
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="onThiTH2")]
	public partial class de2DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertGIANG_VIEN(GIANG_VIEN instance);
    partial void UpdateGIANG_VIEN(GIANG_VIEN instance);
    partial void DeleteGIANG_VIEN(GIANG_VIEN instance);
    partial void InsertSO_DAU_BAI(SO_DAU_BAI instance);
    partial void UpdateSO_DAU_BAI(SO_DAU_BAI instance);
    partial void DeleteSO_DAU_BAI(SO_DAU_BAI instance);
    partial void InsertHOC_KY(HOC_KY instance);
    partial void UpdateHOC_KY(HOC_KY instance);
    partial void DeleteHOC_KY(HOC_KY instance);
    partial void InsertLOP(LOP instance);
    partial void UpdateLOP(LOP instance);
    partial void DeleteLOP(LOP instance);
    partial void InsertMON_HOC(MON_HOC instance);
    partial void UpdateMON_HOC(MON_HOC instance);
    partial void DeleteMON_HOC(MON_HOC instance);
    partial void InsertQUATRINH_HOCTAP(QUATRINH_HOCTAP instance);
    partial void UpdateQUATRINH_HOCTAP(QUATRINH_HOCTAP instance);
    partial void DeleteQUATRINH_HOCTAP(QUATRINH_HOCTAP instance);
    partial void InsertSINH_VIEN(SINH_VIEN instance);
    partial void UpdateSINH_VIEN(SINH_VIEN instance);
    partial void DeleteSINH_VIEN(SINH_VIEN instance);
    #endregion
		
		public de2DataContext() : 
				base(global::thi_de2.Properties.Settings.Default.onThiTH2ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public de2DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public de2DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public de2DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public de2DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<GIANG_VIEN> GIANG_VIENs
		{
			get
			{
				return this.GetTable<GIANG_VIEN>();
			}
		}
		
		public System.Data.Linq.Table<SO_DAU_BAI> SO_DAU_BAIs
		{
			get
			{
				return this.GetTable<SO_DAU_BAI>();
			}
		}
		
		public System.Data.Linq.Table<HOC_KY> HOC_Kies
		{
			get
			{
				return this.GetTable<HOC_KY>();
			}
		}
		
		public System.Data.Linq.Table<LOP> LOPs
		{
			get
			{
				return this.GetTable<LOP>();
			}
		}
		
		public System.Data.Linq.Table<MON_HOC> MON_HOCs
		{
			get
			{
				return this.GetTable<MON_HOC>();
			}
		}
		
		public System.Data.Linq.Table<QUATRINH_HOCTAP> QUATRINH_HOCTAPs
		{
			get
			{
				return this.GetTable<QUATRINH_HOCTAP>();
			}
		}
		
		public System.Data.Linq.Table<SINH_VIEN> SINH_VIENs
		{
			get
			{
				return this.GetTable<SINH_VIEN>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GIANG_VIEN")]
	public partial class GIANG_VIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_GV;
		
		private string _Ten_GV;
		
		private string _Sdt_GV;
		
		private string _Email_GV;
		
		private EntitySet<SO_DAU_BAI> _SO_DAU_BAIs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_GVChanging(string value);
    partial void OnMa_GVChanged();
    partial void OnTen_GVChanging(string value);
    partial void OnTen_GVChanged();
    partial void OnSdt_GVChanging(string value);
    partial void OnSdt_GVChanged();
    partial void OnEmail_GVChanging(string value);
    partial void OnEmail_GVChanged();
    #endregion
		
		public GIANG_VIEN()
		{
			this._SO_DAU_BAIs = new EntitySet<SO_DAU_BAI>(new Action<SO_DAU_BAI>(this.attach_SO_DAU_BAIs), new Action<SO_DAU_BAI>(this.detach_SO_DAU_BAIs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_GV", DbType="NVarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_GV
		{
			get
			{
				return this._Ma_GV;
			}
			set
			{
				if ((this._Ma_GV != value))
				{
					this.OnMa_GVChanging(value);
					this.SendPropertyChanging();
					this._Ma_GV = value;
					this.SendPropertyChanged("Ma_GV");
					this.OnMa_GVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_GV", DbType="NVarChar(30)")]
		public string Ten_GV
		{
			get
			{
				return this._Ten_GV;
			}
			set
			{
				if ((this._Ten_GV != value))
				{
					this.OnTen_GVChanging(value);
					this.SendPropertyChanging();
					this._Ten_GV = value;
					this.SendPropertyChanged("Ten_GV");
					this.OnTen_GVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sdt_GV", DbType="NVarChar(15)")]
		public string Sdt_GV
		{
			get
			{
				return this._Sdt_GV;
			}
			set
			{
				if ((this._Sdt_GV != value))
				{
					this.OnSdt_GVChanging(value);
					this.SendPropertyChanging();
					this._Sdt_GV = value;
					this.SendPropertyChanged("Sdt_GV");
					this.OnSdt_GVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email_GV", DbType="NVarChar(30)")]
		public string Email_GV
		{
			get
			{
				return this._Email_GV;
			}
			set
			{
				if ((this._Email_GV != value))
				{
					this.OnEmail_GVChanging(value);
					this.SendPropertyChanging();
					this._Email_GV = value;
					this.SendPropertyChanged("Email_GV");
					this.OnEmail_GVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GIANG_VIEN_SO_DAU_BAI", Storage="_SO_DAU_BAIs", ThisKey="Ma_GV", OtherKey="Ma_GV")]
		public EntitySet<SO_DAU_BAI> SO_DAU_BAIs
		{
			get
			{
				return this._SO_DAU_BAIs;
			}
			set
			{
				this._SO_DAU_BAIs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SO_DAU_BAIs(SO_DAU_BAI entity)
		{
			this.SendPropertyChanging();
			entity.GIANG_VIEN = this;
		}
		
		private void detach_SO_DAU_BAIs(SO_DAU_BAI entity)
		{
			this.SendPropertyChanging();
			entity.GIANG_VIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SO_DAU_BAI")]
	public partial class SO_DAU_BAI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_BH;
		
		private string _Ma_GV;
		
		private string _Ma_HK;
		
		private string _Ma_MH;
		
		private string _Ma_LOP;
		
		private System.DateTime _Thoigian_batdau;
		
		private System.DateTime _Thoigian_ketthuc;
		
		private int _Soluong_vang;
		
		private string _Noidung_BH;
		
		private string _DG_Hoctap;
		
		private string _DG_Renluyen;
		
		private int _Sogio;
		
		private EntitySet<QUATRINH_HOCTAP> _QUATRINH_HOCTAPs;
		
		private EntityRef<GIANG_VIEN> _GIANG_VIEN;
		
		private EntityRef<HOC_KY> _HOC_KY;
		
		private EntityRef<LOP> _LOP;
		
		private EntityRef<MON_HOC> _MON_HOC;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_BHChanging(int value);
    partial void OnID_BHChanged();
    partial void OnMa_GVChanging(string value);
    partial void OnMa_GVChanged();
    partial void OnMa_HKChanging(string value);
    partial void OnMa_HKChanged();
    partial void OnMa_MHChanging(string value);
    partial void OnMa_MHChanged();
    partial void OnMa_LOPChanging(string value);
    partial void OnMa_LOPChanged();
    partial void OnThoigian_batdauChanging(System.DateTime value);
    partial void OnThoigian_batdauChanged();
    partial void OnThoigian_ketthucChanging(System.DateTime value);
    partial void OnThoigian_ketthucChanged();
    partial void OnSoluong_vangChanging(int value);
    partial void OnSoluong_vangChanged();
    partial void OnNoidung_BHChanging(string value);
    partial void OnNoidung_BHChanged();
    partial void OnDG_HoctapChanging(string value);
    partial void OnDG_HoctapChanged();
    partial void OnDG_RenluyenChanging(string value);
    partial void OnDG_RenluyenChanged();
    partial void OnSogioChanging(int value);
    partial void OnSogioChanged();
    #endregion
		
		public SO_DAU_BAI()
		{
			this._QUATRINH_HOCTAPs = new EntitySet<QUATRINH_HOCTAP>(new Action<QUATRINH_HOCTAP>(this.attach_QUATRINH_HOCTAPs), new Action<QUATRINH_HOCTAP>(this.detach_QUATRINH_HOCTAPs));
			this._GIANG_VIEN = default(EntityRef<GIANG_VIEN>);
			this._HOC_KY = default(EntityRef<HOC_KY>);
			this._LOP = default(EntityRef<LOP>);
			this._MON_HOC = default(EntityRef<MON_HOC>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_BH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_BH
		{
			get
			{
				return this._ID_BH;
			}
			set
			{
				if ((this._ID_BH != value))
				{
					this.OnID_BHChanging(value);
					this.SendPropertyChanging();
					this._ID_BH = value;
					this.SendPropertyChanged("ID_BH");
					this.OnID_BHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_GV", DbType="NVarChar(30)")]
		public string Ma_GV
		{
			get
			{
				return this._Ma_GV;
			}
			set
			{
				if ((this._Ma_GV != value))
				{
					if (this._GIANG_VIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_GVChanging(value);
					this.SendPropertyChanging();
					this._Ma_GV = value;
					this.SendPropertyChanged("Ma_GV");
					this.OnMa_GVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_HK", DbType="NVarChar(30)")]
		public string Ma_HK
		{
			get
			{
				return this._Ma_HK;
			}
			set
			{
				if ((this._Ma_HK != value))
				{
					if (this._HOC_KY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_HKChanging(value);
					this.SendPropertyChanging();
					this._Ma_HK = value;
					this.SendPropertyChanged("Ma_HK");
					this.OnMa_HKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_MH", DbType="NVarChar(30)")]
		public string Ma_MH
		{
			get
			{
				return this._Ma_MH;
			}
			set
			{
				if ((this._Ma_MH != value))
				{
					if (this._MON_HOC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_MHChanging(value);
					this.SendPropertyChanging();
					this._Ma_MH = value;
					this.SendPropertyChanged("Ma_MH");
					this.OnMa_MHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_LOP", DbType="NVarChar(30)")]
		public string Ma_LOP
		{
			get
			{
				return this._Ma_LOP;
			}
			set
			{
				if ((this._Ma_LOP != value))
				{
					if (this._LOP.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_LOPChanging(value);
					this.SendPropertyChanging();
					this._Ma_LOP = value;
					this.SendPropertyChanged("Ma_LOP");
					this.OnMa_LOPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thoigian_batdau", DbType="DateTime NOT NULL")]
		public System.DateTime Thoigian_batdau
		{
			get
			{
				return this._Thoigian_batdau;
			}
			set
			{
				if ((this._Thoigian_batdau != value))
				{
					this.OnThoigian_batdauChanging(value);
					this.SendPropertyChanging();
					this._Thoigian_batdau = value;
					this.SendPropertyChanged("Thoigian_batdau");
					this.OnThoigian_batdauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thoigian_ketthuc", DbType="DateTime NOT NULL")]
		public System.DateTime Thoigian_ketthuc
		{
			get
			{
				return this._Thoigian_ketthuc;
			}
			set
			{
				if ((this._Thoigian_ketthuc != value))
				{
					this.OnThoigian_ketthucChanging(value);
					this.SendPropertyChanging();
					this._Thoigian_ketthuc = value;
					this.SendPropertyChanged("Thoigian_ketthuc");
					this.OnThoigian_ketthucChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Soluong_vang", DbType="Int NOT NULL")]
		public int Soluong_vang
		{
			get
			{
				return this._Soluong_vang;
			}
			set
			{
				if ((this._Soluong_vang != value))
				{
					this.OnSoluong_vangChanging(value);
					this.SendPropertyChanging();
					this._Soluong_vang = value;
					this.SendPropertyChanged("Soluong_vang");
					this.OnSoluong_vangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Noidung_BH", DbType="NVarChar(40)")]
		public string Noidung_BH
		{
			get
			{
				return this._Noidung_BH;
			}
			set
			{
				if ((this._Noidung_BH != value))
				{
					this.OnNoidung_BHChanging(value);
					this.SendPropertyChanging();
					this._Noidung_BH = value;
					this.SendPropertyChanged("Noidung_BH");
					this.OnNoidung_BHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_Hoctap", DbType="NVarChar(40)")]
		public string DG_Hoctap
		{
			get
			{
				return this._DG_Hoctap;
			}
			set
			{
				if ((this._DG_Hoctap != value))
				{
					this.OnDG_HoctapChanging(value);
					this.SendPropertyChanging();
					this._DG_Hoctap = value;
					this.SendPropertyChanged("DG_Hoctap");
					this.OnDG_HoctapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DG_Renluyen", DbType="NVarChar(40)")]
		public string DG_Renluyen
		{
			get
			{
				return this._DG_Renluyen;
			}
			set
			{
				if ((this._DG_Renluyen != value))
				{
					this.OnDG_RenluyenChanging(value);
					this.SendPropertyChanging();
					this._DG_Renluyen = value;
					this.SendPropertyChanged("DG_Renluyen");
					this.OnDG_RenluyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sogio", DbType="Int NOT NULL")]
		public int Sogio
		{
			get
			{
				return this._Sogio;
			}
			set
			{
				if ((this._Sogio != value))
				{
					this.OnSogioChanging(value);
					this.SendPropertyChanging();
					this._Sogio = value;
					this.SendPropertyChanged("Sogio");
					this.OnSogioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SO_DAU_BAI_QUATRINH_HOCTAP", Storage="_QUATRINH_HOCTAPs", ThisKey="ID_BH", OtherKey="Ngay_lenlop")]
		public EntitySet<QUATRINH_HOCTAP> QUATRINH_HOCTAPs
		{
			get
			{
				return this._QUATRINH_HOCTAPs;
			}
			set
			{
				this._QUATRINH_HOCTAPs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GIANG_VIEN_SO_DAU_BAI", Storage="_GIANG_VIEN", ThisKey="Ma_GV", OtherKey="Ma_GV", IsForeignKey=true)]
		public GIANG_VIEN GIANG_VIEN
		{
			get
			{
				return this._GIANG_VIEN.Entity;
			}
			set
			{
				GIANG_VIEN previousValue = this._GIANG_VIEN.Entity;
				if (((previousValue != value) 
							|| (this._GIANG_VIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GIANG_VIEN.Entity = null;
						previousValue.SO_DAU_BAIs.Remove(this);
					}
					this._GIANG_VIEN.Entity = value;
					if ((value != null))
					{
						value.SO_DAU_BAIs.Add(this);
						this._Ma_GV = value.Ma_GV;
					}
					else
					{
						this._Ma_GV = default(string);
					}
					this.SendPropertyChanged("GIANG_VIEN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOC_KY_SO_DAU_BAI", Storage="_HOC_KY", ThisKey="Ma_HK", OtherKey="Ma_HK", IsForeignKey=true)]
		public HOC_KY HOC_KY
		{
			get
			{
				return this._HOC_KY.Entity;
			}
			set
			{
				HOC_KY previousValue = this._HOC_KY.Entity;
				if (((previousValue != value) 
							|| (this._HOC_KY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HOC_KY.Entity = null;
						previousValue.SO_DAU_BAIs.Remove(this);
					}
					this._HOC_KY.Entity = value;
					if ((value != null))
					{
						value.SO_DAU_BAIs.Add(this);
						this._Ma_HK = value.Ma_HK;
					}
					else
					{
						this._Ma_HK = default(string);
					}
					this.SendPropertyChanged("HOC_KY");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOP_SO_DAU_BAI", Storage="_LOP", ThisKey="Ma_LOP", OtherKey="Ma_LOP", IsForeignKey=true)]
		public LOP LOP
		{
			get
			{
				return this._LOP.Entity;
			}
			set
			{
				LOP previousValue = this._LOP.Entity;
				if (((previousValue != value) 
							|| (this._LOP.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOP.Entity = null;
						previousValue.SO_DAU_BAIs.Remove(this);
					}
					this._LOP.Entity = value;
					if ((value != null))
					{
						value.SO_DAU_BAIs.Add(this);
						this._Ma_LOP = value.Ma_LOP;
					}
					else
					{
						this._Ma_LOP = default(string);
					}
					this.SendPropertyChanged("LOP");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MON_HOC_SO_DAU_BAI", Storage="_MON_HOC", ThisKey="Ma_MH", OtherKey="Ma_MH", IsForeignKey=true)]
		public MON_HOC MON_HOC
		{
			get
			{
				return this._MON_HOC.Entity;
			}
			set
			{
				MON_HOC previousValue = this._MON_HOC.Entity;
				if (((previousValue != value) 
							|| (this._MON_HOC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MON_HOC.Entity = null;
						previousValue.SO_DAU_BAIs.Remove(this);
					}
					this._MON_HOC.Entity = value;
					if ((value != null))
					{
						value.SO_DAU_BAIs.Add(this);
						this._Ma_MH = value.Ma_MH;
					}
					else
					{
						this._Ma_MH = default(string);
					}
					this.SendPropertyChanged("MON_HOC");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_QUATRINH_HOCTAPs(QUATRINH_HOCTAP entity)
		{
			this.SendPropertyChanging();
			entity.SO_DAU_BAI = this;
		}
		
		private void detach_QUATRINH_HOCTAPs(QUATRINH_HOCTAP entity)
		{
			this.SendPropertyChanging();
			entity.SO_DAU_BAI = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOC_KY")]
	public partial class HOC_KY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_HK;
		
		private string _Namhoc;
		
		private string _Hocky;
		
		private EntitySet<SO_DAU_BAI> _SO_DAU_BAIs;
		
		private EntitySet<QUATRINH_HOCTAP> _QUATRINH_HOCTAPs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_HKChanging(string value);
    partial void OnMa_HKChanged();
    partial void OnNamhocChanging(string value);
    partial void OnNamhocChanged();
    partial void OnHockyChanging(string value);
    partial void OnHockyChanged();
    #endregion
		
		public HOC_KY()
		{
			this._SO_DAU_BAIs = new EntitySet<SO_DAU_BAI>(new Action<SO_DAU_BAI>(this.attach_SO_DAU_BAIs), new Action<SO_DAU_BAI>(this.detach_SO_DAU_BAIs));
			this._QUATRINH_HOCTAPs = new EntitySet<QUATRINH_HOCTAP>(new Action<QUATRINH_HOCTAP>(this.attach_QUATRINH_HOCTAPs), new Action<QUATRINH_HOCTAP>(this.detach_QUATRINH_HOCTAPs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_HK", DbType="NVarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_HK
		{
			get
			{
				return this._Ma_HK;
			}
			set
			{
				if ((this._Ma_HK != value))
				{
					this.OnMa_HKChanging(value);
					this.SendPropertyChanging();
					this._Ma_HK = value;
					this.SendPropertyChanged("Ma_HK");
					this.OnMa_HKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Namhoc", DbType="NVarChar(30)")]
		public string Namhoc
		{
			get
			{
				return this._Namhoc;
			}
			set
			{
				if ((this._Namhoc != value))
				{
					this.OnNamhocChanging(value);
					this.SendPropertyChanging();
					this._Namhoc = value;
					this.SendPropertyChanged("Namhoc");
					this.OnNamhocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hocky", DbType="NVarChar(30)")]
		public string Hocky
		{
			get
			{
				return this._Hocky;
			}
			set
			{
				if ((this._Hocky != value))
				{
					this.OnHockyChanging(value);
					this.SendPropertyChanging();
					this._Hocky = value;
					this.SendPropertyChanged("Hocky");
					this.OnHockyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOC_KY_SO_DAU_BAI", Storage="_SO_DAU_BAIs", ThisKey="Ma_HK", OtherKey="Ma_HK")]
		public EntitySet<SO_DAU_BAI> SO_DAU_BAIs
		{
			get
			{
				return this._SO_DAU_BAIs;
			}
			set
			{
				this._SO_DAU_BAIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOC_KY_QUATRINH_HOCTAP", Storage="_QUATRINH_HOCTAPs", ThisKey="Ma_HK", OtherKey="Ma_HK")]
		public EntitySet<QUATRINH_HOCTAP> QUATRINH_HOCTAPs
		{
			get
			{
				return this._QUATRINH_HOCTAPs;
			}
			set
			{
				this._QUATRINH_HOCTAPs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SO_DAU_BAIs(SO_DAU_BAI entity)
		{
			this.SendPropertyChanging();
			entity.HOC_KY = this;
		}
		
		private void detach_SO_DAU_BAIs(SO_DAU_BAI entity)
		{
			this.SendPropertyChanging();
			entity.HOC_KY = null;
		}
		
		private void attach_QUATRINH_HOCTAPs(QUATRINH_HOCTAP entity)
		{
			this.SendPropertyChanging();
			entity.HOC_KY = this;
		}
		
		private void detach_QUATRINH_HOCTAPs(QUATRINH_HOCTAP entity)
		{
			this.SendPropertyChanging();
			entity.HOC_KY = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOP")]
	public partial class LOP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_LOP;
		
		private string _Ten_LOP;
		
		private EntitySet<SO_DAU_BAI> _SO_DAU_BAIs;
		
		private EntitySet<SINH_VIEN> _SINH_VIENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_LOPChanging(string value);
    partial void OnMa_LOPChanged();
    partial void OnTen_LOPChanging(string value);
    partial void OnTen_LOPChanged();
    #endregion
		
		public LOP()
		{
			this._SO_DAU_BAIs = new EntitySet<SO_DAU_BAI>(new Action<SO_DAU_BAI>(this.attach_SO_DAU_BAIs), new Action<SO_DAU_BAI>(this.detach_SO_DAU_BAIs));
			this._SINH_VIENs = new EntitySet<SINH_VIEN>(new Action<SINH_VIEN>(this.attach_SINH_VIENs), new Action<SINH_VIEN>(this.detach_SINH_VIENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_LOP", DbType="NVarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_LOP
		{
			get
			{
				return this._Ma_LOP;
			}
			set
			{
				if ((this._Ma_LOP != value))
				{
					this.OnMa_LOPChanging(value);
					this.SendPropertyChanging();
					this._Ma_LOP = value;
					this.SendPropertyChanged("Ma_LOP");
					this.OnMa_LOPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_LOP", DbType="NVarChar(20)")]
		public string Ten_LOP
		{
			get
			{
				return this._Ten_LOP;
			}
			set
			{
				if ((this._Ten_LOP != value))
				{
					this.OnTen_LOPChanging(value);
					this.SendPropertyChanging();
					this._Ten_LOP = value;
					this.SendPropertyChanged("Ten_LOP");
					this.OnTen_LOPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOP_SO_DAU_BAI", Storage="_SO_DAU_BAIs", ThisKey="Ma_LOP", OtherKey="Ma_LOP")]
		public EntitySet<SO_DAU_BAI> SO_DAU_BAIs
		{
			get
			{
				return this._SO_DAU_BAIs;
			}
			set
			{
				this._SO_DAU_BAIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOP_SINH_VIEN", Storage="_SINH_VIENs", ThisKey="Ma_LOP", OtherKey="Ma_LOP")]
		public EntitySet<SINH_VIEN> SINH_VIENs
		{
			get
			{
				return this._SINH_VIENs;
			}
			set
			{
				this._SINH_VIENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SO_DAU_BAIs(SO_DAU_BAI entity)
		{
			this.SendPropertyChanging();
			entity.LOP = this;
		}
		
		private void detach_SO_DAU_BAIs(SO_DAU_BAI entity)
		{
			this.SendPropertyChanging();
			entity.LOP = null;
		}
		
		private void attach_SINH_VIENs(SINH_VIEN entity)
		{
			this.SendPropertyChanging();
			entity.LOP = this;
		}
		
		private void detach_SINH_VIENs(SINH_VIEN entity)
		{
			this.SendPropertyChanging();
			entity.LOP = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MON_HOC")]
	public partial class MON_HOC : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_MH;
		
		private string _Ten_MH;
		
		private int _So_TC;
		
		private int _Sotiet;
		
		private EntitySet<SO_DAU_BAI> _SO_DAU_BAIs;
		
		private EntitySet<QUATRINH_HOCTAP> _QUATRINH_HOCTAPs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_MHChanging(string value);
    partial void OnMa_MHChanged();
    partial void OnTen_MHChanging(string value);
    partial void OnTen_MHChanged();
    partial void OnSo_TCChanging(int value);
    partial void OnSo_TCChanged();
    partial void OnSotietChanging(int value);
    partial void OnSotietChanged();
    #endregion
		
		public MON_HOC()
		{
			this._SO_DAU_BAIs = new EntitySet<SO_DAU_BAI>(new Action<SO_DAU_BAI>(this.attach_SO_DAU_BAIs), new Action<SO_DAU_BAI>(this.detach_SO_DAU_BAIs));
			this._QUATRINH_HOCTAPs = new EntitySet<QUATRINH_HOCTAP>(new Action<QUATRINH_HOCTAP>(this.attach_QUATRINH_HOCTAPs), new Action<QUATRINH_HOCTAP>(this.detach_QUATRINH_HOCTAPs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_MH", DbType="NVarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_MH
		{
			get
			{
				return this._Ma_MH;
			}
			set
			{
				if ((this._Ma_MH != value))
				{
					this.OnMa_MHChanging(value);
					this.SendPropertyChanging();
					this._Ma_MH = value;
					this.SendPropertyChanged("Ma_MH");
					this.OnMa_MHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_MH", DbType="NVarChar(20)")]
		public string Ten_MH
		{
			get
			{
				return this._Ten_MH;
			}
			set
			{
				if ((this._Ten_MH != value))
				{
					this.OnTen_MHChanging(value);
					this.SendPropertyChanging();
					this._Ten_MH = value;
					this.SendPropertyChanged("Ten_MH");
					this.OnTen_MHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_So_TC", DbType="Int NOT NULL")]
		public int So_TC
		{
			get
			{
				return this._So_TC;
			}
			set
			{
				if ((this._So_TC != value))
				{
					this.OnSo_TCChanging(value);
					this.SendPropertyChanging();
					this._So_TC = value;
					this.SendPropertyChanged("So_TC");
					this.OnSo_TCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sotiet", DbType="Int NOT NULL")]
		public int Sotiet
		{
			get
			{
				return this._Sotiet;
			}
			set
			{
				if ((this._Sotiet != value))
				{
					this.OnSotietChanging(value);
					this.SendPropertyChanging();
					this._Sotiet = value;
					this.SendPropertyChanged("Sotiet");
					this.OnSotietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MON_HOC_SO_DAU_BAI", Storage="_SO_DAU_BAIs", ThisKey="Ma_MH", OtherKey="Ma_MH")]
		public EntitySet<SO_DAU_BAI> SO_DAU_BAIs
		{
			get
			{
				return this._SO_DAU_BAIs;
			}
			set
			{
				this._SO_DAU_BAIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MON_HOC_QUATRINH_HOCTAP", Storage="_QUATRINH_HOCTAPs", ThisKey="Ma_MH", OtherKey="Ma_MH")]
		public EntitySet<QUATRINH_HOCTAP> QUATRINH_HOCTAPs
		{
			get
			{
				return this._QUATRINH_HOCTAPs;
			}
			set
			{
				this._QUATRINH_HOCTAPs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SO_DAU_BAIs(SO_DAU_BAI entity)
		{
			this.SendPropertyChanging();
			entity.MON_HOC = this;
		}
		
		private void detach_SO_DAU_BAIs(SO_DAU_BAI entity)
		{
			this.SendPropertyChanging();
			entity.MON_HOC = null;
		}
		
		private void attach_QUATRINH_HOCTAPs(QUATRINH_HOCTAP entity)
		{
			this.SendPropertyChanging();
			entity.MON_HOC = this;
		}
		
		private void detach_QUATRINH_HOCTAPs(QUATRINH_HOCTAP entity)
		{
			this.SendPropertyChanging();
			entity.MON_HOC = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.QUATRINH_HOCTAP")]
	public partial class QUATRINH_HOCTAP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_SV;
		
		private string _Ma_HK;
		
		private string _Ma_MH;
		
		private int _Ngay_lenlop;
		
		private System.Nullable<bool> _Thamgia_BH;
		
		private EntityRef<HOC_KY> _HOC_KY;
		
		private EntityRef<MON_HOC> _MON_HOC;
		
		private EntityRef<SO_DAU_BAI> _SO_DAU_BAI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_SVChanging(string value);
    partial void OnMa_SVChanged();
    partial void OnMa_HKChanging(string value);
    partial void OnMa_HKChanged();
    partial void OnMa_MHChanging(string value);
    partial void OnMa_MHChanged();
    partial void OnNgay_lenlopChanging(int value);
    partial void OnNgay_lenlopChanged();
    partial void OnThamgia_BHChanging(System.Nullable<bool> value);
    partial void OnThamgia_BHChanged();
    #endregion
		
		public QUATRINH_HOCTAP()
		{
			this._HOC_KY = default(EntityRef<HOC_KY>);
			this._MON_HOC = default(EntityRef<MON_HOC>);
			this._SO_DAU_BAI = default(EntityRef<SO_DAU_BAI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_SV", DbType="NVarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_SV
		{
			get
			{
				return this._Ma_SV;
			}
			set
			{
				if ((this._Ma_SV != value))
				{
					this.OnMa_SVChanging(value);
					this.SendPropertyChanging();
					this._Ma_SV = value;
					this.SendPropertyChanged("Ma_SV");
					this.OnMa_SVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_HK", DbType="NVarChar(30)")]
		public string Ma_HK
		{
			get
			{
				return this._Ma_HK;
			}
			set
			{
				if ((this._Ma_HK != value))
				{
					if (this._HOC_KY.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_HKChanging(value);
					this.SendPropertyChanging();
					this._Ma_HK = value;
					this.SendPropertyChanged("Ma_HK");
					this.OnMa_HKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_MH", DbType="NVarChar(30)")]
		public string Ma_MH
		{
			get
			{
				return this._Ma_MH;
			}
			set
			{
				if ((this._Ma_MH != value))
				{
					if (this._MON_HOC.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_MHChanging(value);
					this.SendPropertyChanging();
					this._Ma_MH = value;
					this.SendPropertyChanged("Ma_MH");
					this.OnMa_MHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay_lenlop", DbType="Int NOT NULL")]
		public int Ngay_lenlop
		{
			get
			{
				return this._Ngay_lenlop;
			}
			set
			{
				if ((this._Ngay_lenlop != value))
				{
					if (this._SO_DAU_BAI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNgay_lenlopChanging(value);
					this.SendPropertyChanging();
					this._Ngay_lenlop = value;
					this.SendPropertyChanged("Ngay_lenlop");
					this.OnNgay_lenlopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thamgia_BH", DbType="Bit")]
		public System.Nullable<bool> Thamgia_BH
		{
			get
			{
				return this._Thamgia_BH;
			}
			set
			{
				if ((this._Thamgia_BH != value))
				{
					this.OnThamgia_BHChanging(value);
					this.SendPropertyChanging();
					this._Thamgia_BH = value;
					this.SendPropertyChanged("Thamgia_BH");
					this.OnThamgia_BHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOC_KY_QUATRINH_HOCTAP", Storage="_HOC_KY", ThisKey="Ma_HK", OtherKey="Ma_HK", IsForeignKey=true)]
		public HOC_KY HOC_KY
		{
			get
			{
				return this._HOC_KY.Entity;
			}
			set
			{
				HOC_KY previousValue = this._HOC_KY.Entity;
				if (((previousValue != value) 
							|| (this._HOC_KY.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HOC_KY.Entity = null;
						previousValue.QUATRINH_HOCTAPs.Remove(this);
					}
					this._HOC_KY.Entity = value;
					if ((value != null))
					{
						value.QUATRINH_HOCTAPs.Add(this);
						this._Ma_HK = value.Ma_HK;
					}
					else
					{
						this._Ma_HK = default(string);
					}
					this.SendPropertyChanged("HOC_KY");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MON_HOC_QUATRINH_HOCTAP", Storage="_MON_HOC", ThisKey="Ma_MH", OtherKey="Ma_MH", IsForeignKey=true)]
		public MON_HOC MON_HOC
		{
			get
			{
				return this._MON_HOC.Entity;
			}
			set
			{
				MON_HOC previousValue = this._MON_HOC.Entity;
				if (((previousValue != value) 
							|| (this._MON_HOC.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MON_HOC.Entity = null;
						previousValue.QUATRINH_HOCTAPs.Remove(this);
					}
					this._MON_HOC.Entity = value;
					if ((value != null))
					{
						value.QUATRINH_HOCTAPs.Add(this);
						this._Ma_MH = value.Ma_MH;
					}
					else
					{
						this._Ma_MH = default(string);
					}
					this.SendPropertyChanged("MON_HOC");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SO_DAU_BAI_QUATRINH_HOCTAP", Storage="_SO_DAU_BAI", ThisKey="Ngay_lenlop", OtherKey="ID_BH", IsForeignKey=true)]
		public SO_DAU_BAI SO_DAU_BAI
		{
			get
			{
				return this._SO_DAU_BAI.Entity;
			}
			set
			{
				SO_DAU_BAI previousValue = this._SO_DAU_BAI.Entity;
				if (((previousValue != value) 
							|| (this._SO_DAU_BAI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SO_DAU_BAI.Entity = null;
						previousValue.QUATRINH_HOCTAPs.Remove(this);
					}
					this._SO_DAU_BAI.Entity = value;
					if ((value != null))
					{
						value.QUATRINH_HOCTAPs.Add(this);
						this._Ngay_lenlop = value.ID_BH;
					}
					else
					{
						this._Ngay_lenlop = default(int);
					}
					this.SendPropertyChanged("SO_DAU_BAI");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SINH_VIEN")]
	public partial class SINH_VIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_SV;
		
		private string _Ten_SV;
		
		private string _Sdt_SV;
		
		private string _Email;
		
		private string _Ma_LOP;
		
		private EntityRef<LOP> _LOP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_SVChanging(string value);
    partial void OnMa_SVChanged();
    partial void OnTen_SVChanging(string value);
    partial void OnTen_SVChanged();
    partial void OnSdt_SVChanging(string value);
    partial void OnSdt_SVChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnMa_LOPChanging(string value);
    partial void OnMa_LOPChanged();
    #endregion
		
		public SINH_VIEN()
		{
			this._LOP = default(EntityRef<LOP>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_SV", DbType="NVarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_SV
		{
			get
			{
				return this._Ma_SV;
			}
			set
			{
				if ((this._Ma_SV != value))
				{
					this.OnMa_SVChanging(value);
					this.SendPropertyChanging();
					this._Ma_SV = value;
					this.SendPropertyChanged("Ma_SV");
					this.OnMa_SVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_SV", DbType="NVarChar(20)")]
		public string Ten_SV
		{
			get
			{
				return this._Ten_SV;
			}
			set
			{
				if ((this._Ten_SV != value))
				{
					this.OnTen_SVChanging(value);
					this.SendPropertyChanging();
					this._Ten_SV = value;
					this.SendPropertyChanged("Ten_SV");
					this.OnTen_SVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sdt_SV", DbType="NVarChar(20)")]
		public string Sdt_SV
		{
			get
			{
				return this._Sdt_SV;
			}
			set
			{
				if ((this._Sdt_SV != value))
				{
					this.OnSdt_SVChanging(value);
					this.SendPropertyChanging();
					this._Sdt_SV = value;
					this.SendPropertyChanged("Sdt_SV");
					this.OnSdt_SVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(20)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_LOP", DbType="NVarChar(30)")]
		public string Ma_LOP
		{
			get
			{
				return this._Ma_LOP;
			}
			set
			{
				if ((this._Ma_LOP != value))
				{
					if (this._LOP.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_LOPChanging(value);
					this.SendPropertyChanging();
					this._Ma_LOP = value;
					this.SendPropertyChanged("Ma_LOP");
					this.OnMa_LOPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOP_SINH_VIEN", Storage="_LOP", ThisKey="Ma_LOP", OtherKey="Ma_LOP", IsForeignKey=true)]
		public LOP LOP
		{
			get
			{
				return this._LOP.Entity;
			}
			set
			{
				LOP previousValue = this._LOP.Entity;
				if (((previousValue != value) 
							|| (this._LOP.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOP.Entity = null;
						previousValue.SINH_VIENs.Remove(this);
					}
					this._LOP.Entity = value;
					if ((value != null))
					{
						value.SINH_VIENs.Add(this);
						this._Ma_LOP = value.Ma_LOP;
					}
					else
					{
						this._Ma_LOP = default(string);
					}
					this.SendPropertyChanged("LOP");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
