#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnTH1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="onthiTH1")]
	public partial class OnTH1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertGIANG_VIEN(GIANG_VIEN instance);
    partial void UpdateGIANG_VIEN(GIANG_VIEN instance);
    partial void DeleteGIANG_VIEN(GIANG_VIEN instance);
    partial void InsertTHIET_BI(THIET_BI instance);
    partial void UpdateTHIET_BI(THIET_BI instance);
    partial void DeleteTHIET_BI(THIET_BI instance);
    partial void InsertPHONG(PHONG instance);
    partial void UpdatePHONG(PHONG instance);
    partial void DeletePHONG(PHONG instance);
    partial void InsertSUA_CHUA(SUA_CHUA instance);
    partial void UpdateSUA_CHUA(SUA_CHUA instance);
    partial void DeleteSUA_CHUA(SUA_CHUA instance);
    partial void InsertTHANH_LY(THANH_LY instance);
    partial void UpdateTHANH_LY(THANH_LY instance);
    partial void DeleteTHANH_LY(THANH_LY instance);
    #endregion
		
		public OnTH1DataContext() : 
				base(global::OnTH1.Properties.Settings.Default.onthiTH1ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public OnTH1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OnTH1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OnTH1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OnTH1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<GIANG_VIEN> GIANG_VIENs
		{
			get
			{
				return this.GetTable<GIANG_VIEN>();
			}
		}
		
		public System.Data.Linq.Table<THIET_BI> THIET_BIs
		{
			get
			{
				return this.GetTable<THIET_BI>();
			}
		}
		
		public System.Data.Linq.Table<PHONG> PHONGs
		{
			get
			{
				return this.GetTable<PHONG>();
			}
		}
		
		public System.Data.Linq.Table<SUA_CHUA> SUA_CHUAs
		{
			get
			{
				return this.GetTable<SUA_CHUA>();
			}
		}
		
		public System.Data.Linq.Table<THANH_LY> THANH_Lies
		{
			get
			{
				return this.GetTable<THANH_LY>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.GIANG_VIEN")]
	public partial class GIANG_VIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_GV;
		
		private string _Ten_GV;
		
		private string _Sdt_GV;
		
		private string _Email_GV;
		
		private EntitySet<PHONG> _PHONGs;
		
		private EntitySet<THANH_LY> _THANH_Lies;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_GVChanging(string value);
    partial void OnMa_GVChanged();
    partial void OnTen_GVChanging(string value);
    partial void OnTen_GVChanged();
    partial void OnSdt_GVChanging(string value);
    partial void OnSdt_GVChanged();
    partial void OnEmail_GVChanging(string value);
    partial void OnEmail_GVChanged();
    #endregion
		
		public GIANG_VIEN()
		{
			this._PHONGs = new EntitySet<PHONG>(new Action<PHONG>(this.attach_PHONGs), new Action<PHONG>(this.detach_PHONGs));
			this._THANH_Lies = new EntitySet<THANH_LY>(new Action<THANH_LY>(this.attach_THANH_Lies), new Action<THANH_LY>(this.detach_THANH_Lies));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_GV", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_GV
		{
			get
			{
				return this._Ma_GV;
			}
			set
			{
				if ((this._Ma_GV != value))
				{
					this.OnMa_GVChanging(value);
					this.SendPropertyChanging();
					this._Ma_GV = value;
					this.SendPropertyChanged("Ma_GV");
					this.OnMa_GVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_GV", DbType="NVarChar(30)")]
		public string Ten_GV
		{
			get
			{
				return this._Ten_GV;
			}
			set
			{
				if ((this._Ten_GV != value))
				{
					this.OnTen_GVChanging(value);
					this.SendPropertyChanging();
					this._Ten_GV = value;
					this.SendPropertyChanged("Ten_GV");
					this.OnTen_GVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sdt_GV", DbType="NVarChar(15)")]
		public string Sdt_GV
		{
			get
			{
				return this._Sdt_GV;
			}
			set
			{
				if ((this._Sdt_GV != value))
				{
					this.OnSdt_GVChanging(value);
					this.SendPropertyChanging();
					this._Sdt_GV = value;
					this.SendPropertyChanged("Sdt_GV");
					this.OnSdt_GVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email_GV", DbType="NVarChar(30)")]
		public string Email_GV
		{
			get
			{
				return this._Email_GV;
			}
			set
			{
				if ((this._Email_GV != value))
				{
					this.OnEmail_GVChanging(value);
					this.SendPropertyChanging();
					this._Email_GV = value;
					this.SendPropertyChanged("Email_GV");
					this.OnEmail_GVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GIANG_VIEN_PHONG", Storage="_PHONGs", ThisKey="Ma_GV", OtherKey="Nguoi_quanly")]
		public EntitySet<PHONG> PHONGs
		{
			get
			{
				return this._PHONGs;
			}
			set
			{
				this._PHONGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GIANG_VIEN_THANH_LY", Storage="_THANH_Lies", ThisKey="Ma_GV", OtherKey="Nguoinhan_TB")]
		public EntitySet<THANH_LY> THANH_Lies
		{
			get
			{
				return this._THANH_Lies;
			}
			set
			{
				this._THANH_Lies.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_PHONGs(PHONG entity)
		{
			this.SendPropertyChanging();
			entity.GIANG_VIEN = this;
		}
		
		private void detach_PHONGs(PHONG entity)
		{
			this.SendPropertyChanging();
			entity.GIANG_VIEN = null;
		}
		
		private void attach_THANH_Lies(THANH_LY entity)
		{
			this.SendPropertyChanging();
			entity.GIANG_VIEN = this;
		}
		
		private void detach_THANH_Lies(THANH_LY entity)
		{
			this.SendPropertyChanging();
			entity.GIANG_VIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THIET_BI")]
	public partial class THIET_BI : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_TB;
		
		private string _Ten_TB;
		
		private string _Code_TB;
		
		private System.DateTime _Ngaynhap_TB;
		
		private string _Thongtin_TB;
		
		private string _Vitri_truoc_TB;
		
		private string _Vitri_hientai_TB;
		
		private string _Tinhtrang_TB;
		
		private EntitySet<SUA_CHUA> _SUA_CHUAs;
		
		private EntitySet<THANH_LY> _THANH_Lies;
		
		private EntityRef<PHONG> _PHONG;
		
		private EntityRef<PHONG> _PHONG1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_TBChanging(string value);
    partial void OnMa_TBChanged();
    partial void OnTen_TBChanging(string value);
    partial void OnTen_TBChanged();
    partial void OnCode_TBChanging(string value);
    partial void OnCode_TBChanged();
    partial void OnNgaynhap_TBChanging(System.DateTime value);
    partial void OnNgaynhap_TBChanged();
    partial void OnThongtin_TBChanging(string value);
    partial void OnThongtin_TBChanged();
    partial void OnVitri_truoc_TBChanging(string value);
    partial void OnVitri_truoc_TBChanged();
    partial void OnVitri_hientai_TBChanging(string value);
    partial void OnVitri_hientai_TBChanged();
    partial void OnTinhtrang_TBChanging(string value);
    partial void OnTinhtrang_TBChanged();
    #endregion
		
		public THIET_BI()
		{
			this._SUA_CHUAs = new EntitySet<SUA_CHUA>(new Action<SUA_CHUA>(this.attach_SUA_CHUAs), new Action<SUA_CHUA>(this.detach_SUA_CHUAs));
			this._THANH_Lies = new EntitySet<THANH_LY>(new Action<THANH_LY>(this.attach_THANH_Lies), new Action<THANH_LY>(this.detach_THANH_Lies));
			this._PHONG = default(EntityRef<PHONG>);
			this._PHONG1 = default(EntityRef<PHONG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_TB", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_TB
		{
			get
			{
				return this._Ma_TB;
			}
			set
			{
				if ((this._Ma_TB != value))
				{
					this.OnMa_TBChanging(value);
					this.SendPropertyChanging();
					this._Ma_TB = value;
					this.SendPropertyChanged("Ma_TB");
					this.OnMa_TBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_TB", DbType="NVarChar(30)")]
		public string Ten_TB
		{
			get
			{
				return this._Ten_TB;
			}
			set
			{
				if ((this._Ten_TB != value))
				{
					this.OnTen_TBChanging(value);
					this.SendPropertyChanging();
					this._Ten_TB = value;
					this.SendPropertyChanged("Ten_TB");
					this.OnTen_TBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Code_TB", DbType="NVarChar(30)")]
		public string Code_TB
		{
			get
			{
				return this._Code_TB;
			}
			set
			{
				if ((this._Code_TB != value))
				{
					this.OnCode_TBChanging(value);
					this.SendPropertyChanging();
					this._Code_TB = value;
					this.SendPropertyChanged("Code_TB");
					this.OnCode_TBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaynhap_TB", DbType="DateTime NOT NULL")]
		public System.DateTime Ngaynhap_TB
		{
			get
			{
				return this._Ngaynhap_TB;
			}
			set
			{
				if ((this._Ngaynhap_TB != value))
				{
					this.OnNgaynhap_TBChanging(value);
					this.SendPropertyChanging();
					this._Ngaynhap_TB = value;
					this.SendPropertyChanged("Ngaynhap_TB");
					this.OnNgaynhap_TBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Thongtin_TB", DbType="NVarChar(30)")]
		public string Thongtin_TB
		{
			get
			{
				return this._Thongtin_TB;
			}
			set
			{
				if ((this._Thongtin_TB != value))
				{
					this.OnThongtin_TBChanging(value);
					this.SendPropertyChanging();
					this._Thongtin_TB = value;
					this.SendPropertyChanged("Thongtin_TB");
					this.OnThongtin_TBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vitri_truoc_TB", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Vitri_truoc_TB
		{
			get
			{
				return this._Vitri_truoc_TB;
			}
			set
			{
				if ((this._Vitri_truoc_TB != value))
				{
					if (this._PHONG1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnVitri_truoc_TBChanging(value);
					this.SendPropertyChanging();
					this._Vitri_truoc_TB = value;
					this.SendPropertyChanged("Vitri_truoc_TB");
					this.OnVitri_truoc_TBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vitri_hientai_TB", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Vitri_hientai_TB
		{
			get
			{
				return this._Vitri_hientai_TB;
			}
			set
			{
				if ((this._Vitri_hientai_TB != value))
				{
					if (this._PHONG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnVitri_hientai_TBChanging(value);
					this.SendPropertyChanging();
					this._Vitri_hientai_TB = value;
					this.SendPropertyChanged("Vitri_hientai_TB");
					this.OnVitri_hientai_TBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tinhtrang_TB", DbType="NVarChar(40)")]
		public string Tinhtrang_TB
		{
			get
			{
				return this._Tinhtrang_TB;
			}
			set
			{
				if ((this._Tinhtrang_TB != value))
				{
					this.OnTinhtrang_TBChanging(value);
					this.SendPropertyChanging();
					this._Tinhtrang_TB = value;
					this.SendPropertyChanged("Tinhtrang_TB");
					this.OnTinhtrang_TBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THIET_BI_SUA_CHUA", Storage="_SUA_CHUAs", ThisKey="Ma_TB", OtherKey="Ma_TB")]
		public EntitySet<SUA_CHUA> SUA_CHUAs
		{
			get
			{
				return this._SUA_CHUAs;
			}
			set
			{
				this._SUA_CHUAs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THIET_BI_THANH_LY", Storage="_THANH_Lies", ThisKey="Ma_TB", OtherKey="Ma_TB")]
		public EntitySet<THANH_LY> THANH_Lies
		{
			get
			{
				return this._THANH_Lies;
			}
			set
			{
				this._THANH_Lies.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHONG_THIET_BI", Storage="_PHONG", ThisKey="Vitri_hientai_TB", OtherKey="Ma_phong", IsForeignKey=true)]
		public PHONG PHONG
		{
			get
			{
				return this._PHONG.Entity;
			}
			set
			{
				PHONG previousValue = this._PHONG.Entity;
				if (((previousValue != value) 
							|| (this._PHONG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHONG.Entity = null;
						previousValue.THIET_BIs.Remove(this);
					}
					this._PHONG.Entity = value;
					if ((value != null))
					{
						value.THIET_BIs.Add(this);
						this._Vitri_hientai_TB = value.Ma_phong;
					}
					else
					{
						this._Vitri_hientai_TB = default(string);
					}
					this.SendPropertyChanged("PHONG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHONG_THIET_BI1", Storage="_PHONG1", ThisKey="Vitri_truoc_TB", OtherKey="Ma_phong", IsForeignKey=true)]
		public PHONG PHONG1
		{
			get
			{
				return this._PHONG1.Entity;
			}
			set
			{
				PHONG previousValue = this._PHONG1.Entity;
				if (((previousValue != value) 
							|| (this._PHONG1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._PHONG1.Entity = null;
						previousValue.THIET_BIs1.Remove(this);
					}
					this._PHONG1.Entity = value;
					if ((value != null))
					{
						value.THIET_BIs1.Add(this);
						this._Vitri_truoc_TB = value.Ma_phong;
					}
					else
					{
						this._Vitri_truoc_TB = default(string);
					}
					this.SendPropertyChanged("PHONG1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SUA_CHUAs(SUA_CHUA entity)
		{
			this.SendPropertyChanging();
			entity.THIET_BI = this;
		}
		
		private void detach_SUA_CHUAs(SUA_CHUA entity)
		{
			this.SendPropertyChanging();
			entity.THIET_BI = null;
		}
		
		private void attach_THANH_Lies(THANH_LY entity)
		{
			this.SendPropertyChanging();
			entity.THIET_BI = this;
		}
		
		private void detach_THANH_Lies(THANH_LY entity)
		{
			this.SendPropertyChanging();
			entity.THIET_BI = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHONG")]
	public partial class PHONG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_phong;
		
		private string _Ten_phong;
		
		private string _Vitri_phong;
		
		private string _Nguoi_quanly;
		
		private EntitySet<THIET_BI> _THIET_BIs;
		
		private EntitySet<THIET_BI> _THIET_BIs1;
		
		private EntityRef<GIANG_VIEN> _GIANG_VIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_phongChanging(string value);
    partial void OnMa_phongChanged();
    partial void OnTen_phongChanging(string value);
    partial void OnTen_phongChanged();
    partial void OnVitri_phongChanging(string value);
    partial void OnVitri_phongChanged();
    partial void OnNguoi_quanlyChanging(string value);
    partial void OnNguoi_quanlyChanged();
    #endregion
		
		public PHONG()
		{
			this._THIET_BIs = new EntitySet<THIET_BI>(new Action<THIET_BI>(this.attach_THIET_BIs), new Action<THIET_BI>(this.detach_THIET_BIs));
			this._THIET_BIs1 = new EntitySet<THIET_BI>(new Action<THIET_BI>(this.attach_THIET_BIs1), new Action<THIET_BI>(this.detach_THIET_BIs1));
			this._GIANG_VIEN = default(EntityRef<GIANG_VIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_phong", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_phong
		{
			get
			{
				return this._Ma_phong;
			}
			set
			{
				if ((this._Ma_phong != value))
				{
					this.OnMa_phongChanging(value);
					this.SendPropertyChanging();
					this._Ma_phong = value;
					this.SendPropertyChanged("Ma_phong");
					this.OnMa_phongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_phong", DbType="NVarChar(30)")]
		public string Ten_phong
		{
			get
			{
				return this._Ten_phong;
			}
			set
			{
				if ((this._Ten_phong != value))
				{
					this.OnTen_phongChanging(value);
					this.SendPropertyChanging();
					this._Ten_phong = value;
					this.SendPropertyChanged("Ten_phong");
					this.OnTen_phongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Vitri_phong", DbType="NVarChar(30)")]
		public string Vitri_phong
		{
			get
			{
				return this._Vitri_phong;
			}
			set
			{
				if ((this._Vitri_phong != value))
				{
					this.OnVitri_phongChanging(value);
					this.SendPropertyChanging();
					this._Vitri_phong = value;
					this.SendPropertyChanged("Vitri_phong");
					this.OnVitri_phongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nguoi_quanly", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Nguoi_quanly
		{
			get
			{
				return this._Nguoi_quanly;
			}
			set
			{
				if ((this._Nguoi_quanly != value))
				{
					if (this._GIANG_VIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNguoi_quanlyChanging(value);
					this.SendPropertyChanging();
					this._Nguoi_quanly = value;
					this.SendPropertyChanged("Nguoi_quanly");
					this.OnNguoi_quanlyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHONG_THIET_BI", Storage="_THIET_BIs", ThisKey="Ma_phong", OtherKey="Vitri_hientai_TB")]
		public EntitySet<THIET_BI> THIET_BIs
		{
			get
			{
				return this._THIET_BIs;
			}
			set
			{
				this._THIET_BIs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHONG_THIET_BI1", Storage="_THIET_BIs1", ThisKey="Ma_phong", OtherKey="Vitri_truoc_TB")]
		public EntitySet<THIET_BI> THIET_BIs1
		{
			get
			{
				return this._THIET_BIs1;
			}
			set
			{
				this._THIET_BIs1.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GIANG_VIEN_PHONG", Storage="_GIANG_VIEN", ThisKey="Nguoi_quanly", OtherKey="Ma_GV", IsForeignKey=true)]
		public GIANG_VIEN GIANG_VIEN
		{
			get
			{
				return this._GIANG_VIEN.Entity;
			}
			set
			{
				GIANG_VIEN previousValue = this._GIANG_VIEN.Entity;
				if (((previousValue != value) 
							|| (this._GIANG_VIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GIANG_VIEN.Entity = null;
						previousValue.PHONGs.Remove(this);
					}
					this._GIANG_VIEN.Entity = value;
					if ((value != null))
					{
						value.PHONGs.Add(this);
						this._Nguoi_quanly = value.Ma_GV;
					}
					else
					{
						this._Nguoi_quanly = default(string);
					}
					this.SendPropertyChanged("GIANG_VIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_THIET_BIs(THIET_BI entity)
		{
			this.SendPropertyChanging();
			entity.PHONG = this;
		}
		
		private void detach_THIET_BIs(THIET_BI entity)
		{
			this.SendPropertyChanging();
			entity.PHONG = null;
		}
		
		private void attach_THIET_BIs1(THIET_BI entity)
		{
			this.SendPropertyChanging();
			entity.PHONG1 = this;
		}
		
		private void detach_THIET_BIs1(THIET_BI entity)
		{
			this.SendPropertyChanging();
			entity.PHONG1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SUA_CHUA")]
	public partial class SUA_CHUA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_SC;
		
		private string _Ma_TB;
		
		private System.DateTime _Ngaygiao_TB;
		
		private string _Nguoinhan_TB;
		
		private string _Tinhtrang_TB_lucgiao;
		
		private string _Tinhtrang_TB;
		
		private EntityRef<THIET_BI> _THIET_BI;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_SCChanging(string value);
    partial void OnMa_SCChanged();
    partial void OnMa_TBChanging(string value);
    partial void OnMa_TBChanged();
    partial void OnNgaygiao_TBChanging(System.DateTime value);
    partial void OnNgaygiao_TBChanged();
    partial void OnNguoinhan_TBChanging(string value);
    partial void OnNguoinhan_TBChanged();
    partial void OnTinhtrang_TB_lucgiaoChanging(string value);
    partial void OnTinhtrang_TB_lucgiaoChanged();
    partial void OnTinhtrang_TBChanging(string value);
    partial void OnTinhtrang_TBChanged();
    #endregion
		
		public SUA_CHUA()
		{
			this._THIET_BI = default(EntityRef<THIET_BI>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_SC", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_SC
		{
			get
			{
				return this._Ma_SC;
			}
			set
			{
				if ((this._Ma_SC != value))
				{
					this.OnMa_SCChanging(value);
					this.SendPropertyChanging();
					this._Ma_SC = value;
					this.SendPropertyChanged("Ma_SC");
					this.OnMa_SCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_TB", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Ma_TB
		{
			get
			{
				return this._Ma_TB;
			}
			set
			{
				if ((this._Ma_TB != value))
				{
					if (this._THIET_BI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_TBChanging(value);
					this.SendPropertyChanging();
					this._Ma_TB = value;
					this.SendPropertyChanged("Ma_TB");
					this.OnMa_TBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaygiao_TB", DbType="DateTime NOT NULL")]
		public System.DateTime Ngaygiao_TB
		{
			get
			{
				return this._Ngaygiao_TB;
			}
			set
			{
				if ((this._Ngaygiao_TB != value))
				{
					this.OnNgaygiao_TBChanging(value);
					this.SendPropertyChanging();
					this._Ngaygiao_TB = value;
					this.SendPropertyChanged("Ngaygiao_TB");
					this.OnNgaygiao_TBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nguoinhan_TB", DbType="NVarChar(30)")]
		public string Nguoinhan_TB
		{
			get
			{
				return this._Nguoinhan_TB;
			}
			set
			{
				if ((this._Nguoinhan_TB != value))
				{
					this.OnNguoinhan_TBChanging(value);
					this.SendPropertyChanging();
					this._Nguoinhan_TB = value;
					this.SendPropertyChanged("Nguoinhan_TB");
					this.OnNguoinhan_TBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tinhtrang_TB_lucgiao", DbType="NVarChar(60)")]
		public string Tinhtrang_TB_lucgiao
		{
			get
			{
				return this._Tinhtrang_TB_lucgiao;
			}
			set
			{
				if ((this._Tinhtrang_TB_lucgiao != value))
				{
					this.OnTinhtrang_TB_lucgiaoChanging(value);
					this.SendPropertyChanging();
					this._Tinhtrang_TB_lucgiao = value;
					this.SendPropertyChanged("Tinhtrang_TB_lucgiao");
					this.OnTinhtrang_TB_lucgiaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tinhtrang_TB", DbType="NVarChar(60)")]
		public string Tinhtrang_TB
		{
			get
			{
				return this._Tinhtrang_TB;
			}
			set
			{
				if ((this._Tinhtrang_TB != value))
				{
					this.OnTinhtrang_TBChanging(value);
					this.SendPropertyChanging();
					this._Tinhtrang_TB = value;
					this.SendPropertyChanged("Tinhtrang_TB");
					this.OnTinhtrang_TBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THIET_BI_SUA_CHUA", Storage="_THIET_BI", ThisKey="Ma_TB", OtherKey="Ma_TB", IsForeignKey=true)]
		public THIET_BI THIET_BI
		{
			get
			{
				return this._THIET_BI.Entity;
			}
			set
			{
				THIET_BI previousValue = this._THIET_BI.Entity;
				if (((previousValue != value) 
							|| (this._THIET_BI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THIET_BI.Entity = null;
						previousValue.SUA_CHUAs.Remove(this);
					}
					this._THIET_BI.Entity = value;
					if ((value != null))
					{
						value.SUA_CHUAs.Add(this);
						this._Ma_TB = value.Ma_TB;
					}
					else
					{
						this._Ma_TB = default(string);
					}
					this.SendPropertyChanged("THIET_BI");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THANH_LY")]
	public partial class THANH_LY : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ma_TL;
		
		private string _Ma_TB;
		
		private System.DateTime _Ngaygiao_TB;
		
		private string _Nguoinhan_TB;
		
		private EntityRef<THIET_BI> _THIET_BI;
		
		private EntityRef<GIANG_VIEN> _GIANG_VIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMa_TLChanging(string value);
    partial void OnMa_TLChanged();
    partial void OnMa_TBChanging(string value);
    partial void OnMa_TBChanged();
    partial void OnNgaygiao_TBChanging(System.DateTime value);
    partial void OnNgaygiao_TBChanged();
    partial void OnNguoinhan_TBChanging(string value);
    partial void OnNguoinhan_TBChanged();
    #endregion
		
		public THANH_LY()
		{
			this._THIET_BI = default(EntityRef<THIET_BI>);
			this._GIANG_VIEN = default(EntityRef<GIANG_VIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_TL", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Ma_TL
		{
			get
			{
				return this._Ma_TL;
			}
			set
			{
				if ((this._Ma_TL != value))
				{
					this.OnMa_TLChanging(value);
					this.SendPropertyChanging();
					this._Ma_TL = value;
					this.SendPropertyChanged("Ma_TL");
					this.OnMa_TLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ma_TB", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Ma_TB
		{
			get
			{
				return this._Ma_TB;
			}
			set
			{
				if ((this._Ma_TB != value))
				{
					if (this._THIET_BI.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMa_TBChanging(value);
					this.SendPropertyChanging();
					this._Ma_TB = value;
					this.SendPropertyChanged("Ma_TB");
					this.OnMa_TBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngaygiao_TB", DbType="DateTime NOT NULL")]
		public System.DateTime Ngaygiao_TB
		{
			get
			{
				return this._Ngaygiao_TB;
			}
			set
			{
				if ((this._Ngaygiao_TB != value))
				{
					this.OnNgaygiao_TBChanging(value);
					this.SendPropertyChanging();
					this._Ngaygiao_TB = value;
					this.SendPropertyChanged("Ngaygiao_TB");
					this.OnNgaygiao_TBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nguoinhan_TB", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string Nguoinhan_TB
		{
			get
			{
				return this._Nguoinhan_TB;
			}
			set
			{
				if ((this._Nguoinhan_TB != value))
				{
					if (this._GIANG_VIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNguoinhan_TBChanging(value);
					this.SendPropertyChanging();
					this._Nguoinhan_TB = value;
					this.SendPropertyChanged("Nguoinhan_TB");
					this.OnNguoinhan_TBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THIET_BI_THANH_LY", Storage="_THIET_BI", ThisKey="Ma_TB", OtherKey="Ma_TB", IsForeignKey=true)]
		public THIET_BI THIET_BI
		{
			get
			{
				return this._THIET_BI.Entity;
			}
			set
			{
				THIET_BI previousValue = this._THIET_BI.Entity;
				if (((previousValue != value) 
							|| (this._THIET_BI.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THIET_BI.Entity = null;
						previousValue.THANH_Lies.Remove(this);
					}
					this._THIET_BI.Entity = value;
					if ((value != null))
					{
						value.THANH_Lies.Add(this);
						this._Ma_TB = value.Ma_TB;
					}
					else
					{
						this._Ma_TB = default(string);
					}
					this.SendPropertyChanged("THIET_BI");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="GIANG_VIEN_THANH_LY", Storage="_GIANG_VIEN", ThisKey="Nguoinhan_TB", OtherKey="Ma_GV", IsForeignKey=true)]
		public GIANG_VIEN GIANG_VIEN
		{
			get
			{
				return this._GIANG_VIEN.Entity;
			}
			set
			{
				GIANG_VIEN previousValue = this._GIANG_VIEN.Entity;
				if (((previousValue != value) 
							|| (this._GIANG_VIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._GIANG_VIEN.Entity = null;
						previousValue.THANH_Lies.Remove(this);
					}
					this._GIANG_VIEN.Entity = value;
					if ((value != null))
					{
						value.THANH_Lies.Add(this);
						this._Nguoinhan_TB = value.Ma_GV;
					}
					else
					{
						this._Nguoinhan_TB = default(string);
					}
					this.SendPropertyChanged("GIANG_VIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
